#!/bin/sh

# Invoke:
# sh install backup
# sh install link

# Downloaded files
dirhere=~/dotfiles
# Backup folder
dirold=~/.dotfiles-old

# Makefiles might work, but they depend on 'make' being installed.
# This should work with just coreutils available (and a shell).
case "$1" in
    backup)
        # TODO be careful about overwriting existing backups
        mkdir -p "$dirold"
        mv ~/.gitconfig "$dirold/.gitconfig"
        mv ~/.gitignore "$dirold/.gitignore"
        mv ~/lesscolors "$dirold/lesscolors"
        mv ~/.mailcap   "$dirold/.mailcap"
        mv ~/.screenrc  "$dirold/.screenrc"
        mv ~/.vimrc     "$dirold/.vimrc"
        mv ~/.vim       "$dirold/.vim"
        ;;

    restore)
        cp -p  "$dirold/.gitconfig" ~/.gitconfig
        cp -p  "$dirold/.gitignore" ~/.gitignore
        cp -p  "$dirold/lesscolors" ~/lesscolors
        cp -p  "$dirold/.mailcap"   ~/.mailcap
        cp -p  "$dirold/.screenrc"  ~/.screenrc
        cp -p  "$dirold/.vimrc"     ~/.vimrc
        cp -pr "$dirold/.vim"       ~/.vim
        ;;

    link)
        ln -s "$dirhere/gitconfig"  ~/.gitconfig
        ln -s "$dirhere/gitignore"  ~/.gitignore
        ln -s "$dirhere/lesscolors" ~/lesscolors
        ln -s "$dirhere/mailcap"    ~/.mailcap
        ln -s "$dirhere/screenrc"   ~/.screenrc
        ln -s "$dirhere/vimrc"      ~/.vimrc
        ln -s "$dirhere/vim"        ~/.vim
        ;;

    *)
        echo "Not an appropriate action."
        exit 1
esac
